apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: order
  namespace: default
  labels:
    app: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: order:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
          name: orderport
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: default
spec:
  type: NodePort
  selector:
    app: order
  ports:
  - name: orderserviceport
    protocol: TCP
    port: 9090
    targetPort: orderport
